// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: profile/v1/profile.proto

package profile_v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	user "github.com/BlazeCoder04/online_store/services/user/pkg/user"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Get
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *user.User             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetData() *user.User {
	if x != nil {
		return x.Data
	}
	return nil
}

// Update
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NewEmail      *string                `protobuf:"bytes,3,opt,name=new_email,json=newEmail,proto3,oneof" json:"new_email,omitempty"`
	NewPassword   *string                `protobuf:"bytes,4,opt,name=new_password,json=newPassword,proto3,oneof" json:"new_password,omitempty"`
	NewFirstName  *string                `protobuf:"bytes,5,opt,name=new_first_name,json=newFirstName,proto3,oneof" json:"new_first_name,omitempty"`
	NewLastName   *string                `protobuf:"bytes,6,opt,name=new_last_name,json=newLastName,proto3,oneof" json:"new_last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateRequest) GetNewEmail() string {
	if x != nil && x.NewEmail != nil {
		return *x.NewEmail
	}
	return ""
}

func (x *UpdateRequest) GetNewPassword() string {
	if x != nil && x.NewPassword != nil {
		return *x.NewPassword
	}
	return ""
}

func (x *UpdateRequest) GetNewFirstName() string {
	if x != nil && x.NewFirstName != nil {
		return *x.NewFirstName
	}
	return ""
}

func (x *UpdateRequest) GetNewLastName() string {
	if x != nil && x.NewLastName != nil {
		return *x.NewLastName
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *user.User             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_profile_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateResponse) GetData() *user.User {
	if x != nil {
		return x.Data
	}
	return nil
}

// Delete
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_profile_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_profile_v1_profile_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_profile_v1_profile_proto protoreflect.FileDescriptor

const file_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x18profile/v1/profile.proto\x12\n" +
	"profile_v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fuser/user.proto\"/\n" +
	"\n" +
	"GetRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\"-\n" +
	"\vGetResponse\x12\x1e\n" +
	"\x04data\x18\x01 \x01(\v2\n" +
	".user.UserR\x04data\"\xdd\x02\n" +
	"\rUpdateRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x06R\bpassword\x12)\n" +
	"\tnew_email\x18\x03 \x01(\tB\a\xbaH\x04r\x02`\x01H\x00R\bnewEmail\x88\x01\x01\x12/\n" +
	"\fnew_password\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x06H\x01R\vnewPassword\x88\x01\x01\x122\n" +
	"\x0enew_first_name\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x03H\x02R\fnewFirstName\x88\x01\x01\x120\n" +
	"\rnew_last_name\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x03H\x03R\vnewLastName\x88\x01\x01B\f\n" +
	"\n" +
	"_new_emailB\x0f\n" +
	"\r_new_passwordB\x11\n" +
	"\x0f_new_first_nameB\x10\n" +
	"\x0e_new_last_name\"0\n" +
	"\x0eUpdateResponse\x12\x1e\n" +
	"\x04data\x18\x01 \x01(\v2\n" +
	".user.UserR\x04data\"W\n" +
	"\rDeleteRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x06R\bpassword2\xa7\x02\n" +
	"\tProfileV1\x12V\n" +
	"\x03Get\x12\x16.profile_v1.GetRequest\x1a\x17.profile_v1.GetResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/profiles/{user_id}\x12b\n" +
	"\x06Update\x12\x19.profile_v1.UpdateRequest\x1a\x1a.profile_v1.UpdateResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*2\x16/v1/profiles/{user_id}\x12^\n" +
	"\x06Delete\x12\x19.profile_v1.DeleteRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x01**\x16/v1/profiles/{user_id}BNZLgithub.com/BlazeCoder04/online_store/services/user/pkg/profile/v1;profile_v1b\x06proto3"

var (
	file_profile_v1_profile_proto_rawDescOnce sync.Once
	file_profile_v1_profile_proto_rawDescData []byte
)

func file_profile_v1_profile_proto_rawDescGZIP() []byte {
	file_profile_v1_profile_proto_rawDescOnce.Do(func() {
		file_profile_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_v1_profile_proto_rawDesc), len(file_profile_v1_profile_proto_rawDesc)))
	})
	return file_profile_v1_profile_proto_rawDescData
}

var file_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_profile_v1_profile_proto_goTypes = []any{
	(*GetRequest)(nil),     // 0: profile_v1.GetRequest
	(*GetResponse)(nil),    // 1: profile_v1.GetResponse
	(*UpdateRequest)(nil),  // 2: profile_v1.UpdateRequest
	(*UpdateResponse)(nil), // 3: profile_v1.UpdateResponse
	(*DeleteRequest)(nil),  // 4: profile_v1.DeleteRequest
	(*user.User)(nil),      // 5: user.User
	(*emptypb.Empty)(nil),  // 6: google.protobuf.Empty
}
var file_profile_v1_profile_proto_depIdxs = []int32{
	5, // 0: profile_v1.GetResponse.data:type_name -> user.User
	5, // 1: profile_v1.UpdateResponse.data:type_name -> user.User
	0, // 2: profile_v1.ProfileV1.Get:input_type -> profile_v1.GetRequest
	2, // 3: profile_v1.ProfileV1.Update:input_type -> profile_v1.UpdateRequest
	4, // 4: profile_v1.ProfileV1.Delete:input_type -> profile_v1.DeleteRequest
	1, // 5: profile_v1.ProfileV1.Get:output_type -> profile_v1.GetResponse
	3, // 6: profile_v1.ProfileV1.Update:output_type -> profile_v1.UpdateResponse
	6, // 7: profile_v1.ProfileV1.Delete:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_profile_v1_profile_proto_init() }
func file_profile_v1_profile_proto_init() {
	if File_profile_v1_profile_proto != nil {
		return
	}
	file_profile_v1_profile_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_v1_profile_proto_rawDesc), len(file_profile_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_profile_v1_profile_proto_depIdxs,
		MessageInfos:      file_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_profile_v1_profile_proto = out.File
	file_profile_v1_profile_proto_goTypes = nil
	file_profile_v1_profile_proto_depIdxs = nil
}
